services:
  - type: web
    name: student-results-site
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
